# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djbugger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionshistory',
            name='resolved',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Error Resolved'),
        ),
        migrations.AlterField(
            model_name='exceptionshistory',
            name='updated',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Error Updated'),
        ),
        migrations.AlterField(
            model_name='exceptionshistory',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL, verbose_name='User Created Error'),
        ),
    ]
