# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbugger', '0003_auto_20180527_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionshistory',
            name='request_method',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Request Method'),
        ),
        migrations.AddField(
            model_name='exceptionshistory',
            name='request_url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Request URL'),
        ),
        migrations.AddField(
            model_name='exceptionshistory',
            name='url_path',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Request URL PAth'),
        ),
        migrations.AlterField(
            model_name='exceptionshistory',
            name='status',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Exception Status'),
        ),
    ]
