# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-04 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djbugger', '0004_auto_20180602_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionshistory',
            name='bug_type',
            field=models.BooleanField(default=True, help_text='False for manually added issues'),
        ),
    ]
